# Generated by Django 5.2.7 on 2025-10-03 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("profile", models.AutoField(primary_key=True, serialize=False)),
                ("middle_name", models.CharField(max_length=20, null=True)),
                ("email", models.EmailField(max_length=50, null=True, unique=True)),
                (
                    "date_of_birth",
                    models.DateField(blank=True, max_length=20, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=11, null=True, unique=True),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        choices=[
                            ("Nigeria", "Nigeria"),
                            ("Ghana", "Ghana"),
                            ("UK", "UK"),
                            ("USA", "USA"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Alabama", "Alabama"),
                            ("Alaska", "Alaska"),
                            ("Arizona", "Arizona"),
                            ("Arkansas", "Arkansas"),
                            ("California", "California"),
                            ("Colorado", "Colorado"),
                            ("Connecticut", "Connecticut"),
                            ("Delaware", "Delaware"),
                            ("Florida", "Florida"),
                            ("Georgia", "Georgia"),
                            ("Hawaii", "Hawaii"),
                            ("Idaho", "Idaho"),
                            ("Illinois", "Illinois"),
                            ("Indiana", "Indiana"),
                            ("Iowa", "Iowa"),
                            ("Kansas", "Kansas"),
                            ("Kentucky", "Kentucky"),
                            ("Louisiana", "Louisiana"),
                            ("Maine", "Maine"),
                            ("Maryland", "Maryland"),
                            ("Massachusetts", "Massachusetts"),
                            ("Michigan", "Michigan"),
                            ("Minnesota", "Minnesota"),
                            ("Mississippi", "Mississippi"),
                            ("Missouri", "Missouri"),
                            ("Montana", "Montana"),
                            ("Nebraska", "Nebraska"),
                            ("Nevada", "Nevada"),
                            ("New Hampshire", "New Hampshire"),
                            ("New Jersey", "New Jersey"),
                            ("New Mexico", "New Mexico"),
                            ("New York", "New York"),
                            ("North Carolina", "North Carolina"),
                            ("North Dakota", "North Dakota"),
                            ("Ohio", "Ohio"),
                            ("Oklahoma", "Oklahoma"),
                            ("Oregon", "Oregon"),
                            ("Pennsylvania", "Pennsylvania"),
                            ("Rhode Island", "Rhode Island"),
                            ("South Carolina", "South Carolina"),
                            ("South Dakota", "South Dakota"),
                            ("Tennessee", "Tennessee"),
                            ("Texas", "Texas"),
                            ("Utah", "Utah"),
                            ("Vermont", "Vermont"),
                            ("Virginia", "Virginia"),
                            ("Washington", "Washington"),
                            ("West Virginia", "West Virginia"),
                            ("Wisconsin", "Wisconsin"),
                            ("Wyoming", "Wyoming"),
                            ("District of Columbia", "District of Columbia"),
                            ("American Samoa", "American Samoa"),
                            ("Northern Mariana Islands", "Northern Mariana Islands"),
                            ("Puerto Rico", "Puerto Rico"),
                            (
                                "United States Minor Outlying Islands",
                                "United States Minor Outlying Islands",
                            ),
                            ("Virgin Islands, U.S.", "Virgin Islands, U.S."),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("city", models.CharField(max_length=50, null=True)),
                ("address", models.CharField(max_length=100, null=True)),
                ("occupation", models.CharField(max_length=50, null=True)),
                (
                    "profile_passport",
                    models.ImageField(null=True, upload_to="userimage/"),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("CEO", "CEO"),
                            ("GMD", "GMD"),
                            ("CTO", "CTO"),
                            ("Supervisor", "Supervisor"),
                            ("Accountant", "Accountant"),
                            ("Marketer", "Marketer"),
                            ("Cashier", "Cashier"),
                            ("Driver", "Driver"),
                            ("Customer care", "Customer care"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("Single", "Single"),
                            ("Engaged", "Engaged"),
                            ("Married", "Married"),
                            ("Divorce", "Divorce"),
                            ("Complicated", "Complicated"),
                            ("Widow", "Widow"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("staff", models.BooleanField(default=False, null=True)),
                (
                    "user_status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Retired", "Retired"),
                            ("Suspended", "Suspended"),
                            ("Freeze", "Freeze"),
                            ("On Leave", "On Leave"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
